### Treemap에서 사용할 exel을 json으로 변환

In [1]:
import pandas as pd
import numpy as np
import json

In [2]:
df = pd.read_csv("C:/HANSSAK/SecureGate/download/분석본_250528_장기체류(등록+거소)외국인_데이터셋(2015_2024, 202501_04).csv", encoding='cp949')
df

         시도명 자격_대분류  외국인수
0    강원특별자치도      0   112
1    강원특별자치도     A3    12
2    강원특별자치도     D1     1
3    강원특별자치도    D10   332
4    강원특별자치도     D2  5178
..       ...    ...   ...
501     충청북도     F5  4419
502     충청북도     F6  5056
503     충청북도     G1  3171
504     충청북도     H1    14
505     충청북도     H2  2524

[506 rows x 3 columns]

In [ ]:
result = []

for sido, group in df.groupby('시도명'):
    item = []
    for _, row in group.iterrows():
        item.append({
            "자격_대분류": row['자격_대분류'],
            "외국인수": row['외국인수']
        })
        
    result.append({
        "시도명": sido,
        "data": item
    })
    
    
result

[{'시도명': '강원특별자치도',
  'data': [{'자격_대분류': '0', '외국인수': 112},
   {'자격_대분류': 'A3', '외국인수': 12},
   {'자격_대분류': 'D1', '외국인수': 1},
   {'자격_대분류': 'D10', '외국인수': 332},
   {'자격_대분류': 'D2', '외국인수': 5178},
   {'자격_대분류': 'D3', '외국인수': 22},
   {'자격_대분류': 'D4', '외국인수': 2158},
   {'자격_대분류': 'D6', '외국인수': 38},
   {'자격_대분류': 'D7', '외국인수': 1},
   {'자격_대분류': 'D8', '외국인수': 37},
   {'자격_대분류': 'D9', '외국인수': 19},
   {'자격_대분류': 'E1', '외국인수': 29},
   {'자격_대분류': 'E10', '외국인수': 1038},
   {'자격_대분류': 'E2', '외국인수': 396},
   {'자격_대분류': 'E3', '외국인수': 96},
   {'자격_대분류': 'E6', '외국인수': 35},
   {'자격_대분류': 'E7', '외국인수': 511},
   {'자격_대분류': 'E8', '외국인수': 746},
   {'자격_대분류': 'E9', '외국인수': 5717},
   {'자격_대분류': 'F1', '외국인수': 1788},
   {'자격_대분류': 'F2', '외국인수': 391},
   {'자격_대분류': 'F3', '외국인수': 569},
   {'자격_대분류': 'F4', '외국인수': 4144},
   {'자격_대분류': 'F5', '외국인수': 1694},
   {'자격_대분류': 'F6', '외국인수': 3339},
   {'자격_대분류': 'G1', '외국인수': 1385},
   {'자격_대분류': 'H1', '외국인수': 17},
   {'자격_대분류': 'H2', '외국인수': 413}]},
 {'시도명': '경기도',
  'data': [{'자격_대분류': '0', '외국인수': 4361},
   {'자격_대분류': 'A1', '외국인수': 17},
   {'자격_대분류': 'A2', '외국인수': 132},
   {'자격_대분류': 'A3', '외국인수': 7704},
   {'자격_대분류': 'D1', '외국인수': 10},
   {'자격_대분류': 'D10', '외국인수': 2853},
   {'자격_대분류': 'D2', '외국인수': 28564},
   {'자격_대분류': 'D3', '외국인수': 213},
   {'자격_대분류': 'D4', '외국인수': 14244},
   {'자격_대분류': 'D5', '외국인수': 3},
   {'자격_대분류': 'D6', '외국인수': 507},
   {'자격_대분류': 'D7', '외국인수': 153},
   {'자격_대분류': 'D8', '외국인수': 1785},
   {'자격_대분류': 'D9', '외국인수': 335},
   {'자격_대분류': 'E1', '외국인수': 311},
   {'자격_대분류': 'E10', '외국인수': 11},
   {'자격_대분류': 'E2', '외국인수': 3117},
   {'자격_대분류': 'E3', '외국인수': 682},
   {'자격_대분류': 'E4', '외국인수': 5},
   {'자격_대분류': 'E5', '외국인수': 1},
   {'자격_대분류': 'E6', '외국인수': 1152},
   {'자격_대분류': 'E7', '외국인수': 16353},
   {'자격_대분류': 'E8', '외국인수': 500},
   {'자격_대분류': 'E9', '외국인수': 120561},
   {'자격_대분류': 'F1', '외국인수': 31677},
   {'자격_대분류': 'F2', '외국인수': 21309},
   {'자격_대분류': 'F3', '외국인수': 15782},
   {'자격_대분류': 'F4', '외국인수': 239460},
   {'자격_대분류': 'F5', '외국인수': 86777},
   {'자격_대분류': 'F6', '외국인수': 45019},
   {'자격_대분류': 'G1', '외국인수': 19676},
   {'자격_대분류': 'H1', '외국인수': 321},
   {'자격_대분류': 'H2', '외국인수': 43263}]},
 {'시도명': '경상남도',
  'data': [{'자격_대분류': '0', '외국인수': 947},
   {'자격_대분류': 'A2', '외국인수': 27},
   {'자격_대분류': 'A3', '외국인수': 283},
   {'자격_대분류': 'D10', '외국인수': 652},
   {'자격_대분류': 'D2', '외국인수': 3426},
   {'자격_대분류': 'D3', '외국인수': 217},
   {'자격_대분류': 'D4', '외국인수': 2611},
   {'자격_대분류': 'D6', '외국인수': 57},
   {'자격_대분류': 'D7', '외국인수': 83},
   {'자격_대분류': 'D8', '외국인수': 240},
   {'자격_대분류': 'D9', '외국인수': 635},
   {'자격_대분류': 'E1', '외국인수': 30},
   {'자격_대분류': 'E10', '외국인수': 3571},
   {'자격_대분류': 'E2', '외국인수': 591},
   {'자격_대분류': 'E3', '외국인수': 117},
   {'자격_대분류': 'E4', '외국인수': 9},
   {'자격_대분류': 'E6', '외국인수': 271},
   {'자격_대분류': 'E7', '외국인수': 9548},
   {'자격_대분류': 'E8', '외국인수': 3738},
   {'자격_대분류': 'E9', '외국인수': 40717},
   {'자격_대분류': 'F1', '외국인수': 6178},
   {'자격_대분류': 'F2', '외국인수': 2415},
   {'자격_대분류': 'F3', '외국인수': 4277},
   {'자격_대분류': 'F4', '외국인수': 14937},
   {'자격_대분류': 'F5', '외국인수': 5578},
   {'자격_대분류': 'F6', '외국인수': 9510},
   {'자격_대분류': 'G1', '외국인수': 4682},
   {'자격_대분류': 'H1', '외국인수': 33},
   {'자격_대분류': 'H2', '외국인수': 1890}]},
 {'시도명': '경상북도',
  'data': [{'자격_대분류': '0', '외국인수': 546},
   {'자격_대분류': 'A2', '외국인수': 9},
   {'자격_대분류': 'A3', '외국인수': 593},
   {'자격_대분류': 'D1', '외국인수': 1},
   {'자격_대분류': 'D10', '외국인수': 1244},
   {'자격_대분류': 'D2', '외국인수': 10930},
   {'자격_대분류': 'D3', '외국인수': 63},
   {'자격_대분류': 'D4', '외국인수': 6214},
   {'자격_대분류': 'D6', '외국인수': 76},
   {'자격_대분류': 'D7', '외국인수': 4},
   {'자격_대분류': 'D8', '외국인수': 202},
   {'자격_대분류': 'D9', '외국인수': 164},
   {'자격_대분류': 'E1', '외국인수': 223},
   {'자격_대분류': 'E10', '외국인수': 3199},
   {'자격_대분류': 'E2', '외국인수': 426},
   {'자격_대분류': 'E3', '외국인수': 195},
   {'자격_대분류': 'E4', '외국인수': 19},
   {'자격_대분류': 'E6', '외국인수': 120},
   {'자격_대분류': 'E7', '외국인수': 2466},
   {'자격_대분류': 'E8', '외국인수': 2878},
   {'자격_대분류': 'E9', '외국인수': 22347},
   {'자격_대분류': 'F1', '외국인수': 4978},
   {'자격_대분류': 'F2', '외국인수': 1802},
   {'자격_대분류': 'F3', '외국인수': 2597},
   {'자격_대분류': 'F4', '외국인수': 10697},
   {'자격_대분류': 'F5', '외국인수': 3312},
   {'자격_대분류': 'F6', '외국인수': 7266},
   {'자격_대분류': 'G1', '외국인수': 3145},
   {'자격_대분류': 'H1', '외국인수': 48},
   {'자격_대분류': 'H2', '외국인수': 1701}]},
 {'시도명': '광주광역시',
  'data': [{'자격_대분류': '0', '외국인수': 201},
   {'자격_대분류': 'A1', '외국인수': 16},
   {'자격_대분류': 'A2', '외국인수': 4},
   {'자격_대분류': 'A3', '외국인수': 6},
   {'자격_대분류': 'D10', '외국인수': 717},
   {'자격_대분류': 'D2', '외국인수': 5173},
   {'자격_대분류': 'D3', '외국인수': 13},
   {'자격_대분류': 'D4', '외국인수': 2672},
   {'자격_대분류': 'D6', '외국인수': 48},
   {'자격_대분류': 'D7', '외국인수': 2},
   {'자격_대분류': 'D8', '외국인수': 44},
   {'자격_대분류': 'D9', '외국인수': 17},
   {'자격_대분류': 'E1', '외국인수': 37},
   {'자격_대분류': 'E10', '외국인수': 1},
   {'자격_대분류': 'E2', '외국인수': 339},
   {'자격_대분류': 'E3', '외국인수': 162},
   {'자격_대분류': 'E6', '외국인수': 30},
   {'자격_대분류': 'E7', '외국인수': 592},
   {'자격_대분류': 'E8', '외국인수': 14},
   {'자격_대분류': 'E9', '외국인수': 4522},
   {'자격_대분류': 'F1', '외국인수': 3004},
   {'자격_대분류': 'F2', '외국인수': 577},
   {'자격_대분류': 'F3', '외국인수': 967},
   {'자격_대분류': 'F4', '외국인수': 6175},
   {'자격_대분류': 'F5', '외국인수': 1513},
   {'자격_대분류': 'F6', '외국인수': 3311},
   {'자격_대분류': 'G1', '외국인수': 1688},
   {'자격_대분류': 'H1', '외국인수': 12},
   {'자격_대분류': 'H2', '외국인수': 875}]},
 {'시도명': '대구광역시',
  'data': [{'자격_대분류': '0', '외국인수': 398},
   {'자격_대분류': 'A2', '외국인수': 3},
   {'자격_대분류': 'A3', '외국인수': 1090},
   {'자격_대분류': 'D10', '외국인수': 921},
   {'자격_대분류': 'D2', '외국인수': 5494},
   {'자격_대분류': 'D3', '외국인수': 35},
   {'자격_대분류': 'D4', '외국인수': 4132},
   {'자격_대분류': 'D6', '외국인수': 65},
   {'자격_대분류': 'D7', '외국인수': 4},
   {'자격_대분류': 'D8', '외국인수': 139},
   {'자격_대분류': 'D9', '외국인수': 45},
   {'자격_대분류': 'E1', '외국인수': 94},
   {'자격_대분류': 'E10', '외국인수': 2},
   {'자격_대분류': 'E2', '외국인수': 677},
   {'자격_대분류': 'E3', '외국인수': 115},
   {'자격_대분류': 'E4', '외국인수': 1},
   {'자격_대분류': 'E6', '외국인수': 152},
   {'자격_대분류': 'E7', '외국인수': 1177},
   {'자격_대분류': 'E8', '외국인수': 46},
   {'자격_대분류': 'E9', '외국인수': 7417},
   {'자격_대분류': 'F1', '외국인수': 2893},
   {'자격_대분류': 'F2', '외국인수': 1019},
   {'자격_대분류': 'F3', '외국인수': 1261},
   {'자격_대분류': 'F4', '외국인수': 5539},
   {'자격_대분류': 'F5', '외국인수': 2401},
   {'자격_대분류': 'F6', '외국인수': 5204},
   {'자격_대분류': 'G1', '외국인수': 1385},
   {'자격_대분류': 'H1', '외국인수': 39},
   {'자격_대분류': 'H2', '외국인수': 501}]},
 {'시도명': '대전광역시',
  'data': [{'자격_대분류': '0', '외국인수': 63},
   {'자격_대분류': 'A1', '외국인수': 3},
   {'자격_대분류': 'A2', '외국인수': 47},
   {'자격_대분류': 'A3', '외국인수': 17},
   {'자격_대분류': 'D10', '외국인수': 575},
   {'자격_대분류': 'D2', '외국인수': 9302},
   {'자격_대분류': 'D3', '외국인수': 2},
   {'자격_대분류': 'D4', '외국인수': 4501},
   {'자격_대분류': 'D6', '외국인수': 21},
   {'자격_대분류': 'D7', '외국인수': 7},
   {'자격_대분류': 'D8', '외국인수': 40},
   {'자격_대분류': 'D9', '외국인수': 11},
   {'자격_대분류': 'E1', '외국인수': 189},
   {'자격_대분류': 'E2', '외국인수': 423},
   {'자격_대분류': 'E3', '외국인수': 364},
   {'자격_대분류': 'E4', '외국인수': 3},
   {'자격_대분류': 'E6', '외국인수': 32},
   {'자격_대분류': 'E7', '외국인수': 492},
   {'자격_대분류': 'E8', '외국인수': 9},
   {'자격_대분류': 'E9', '외국인수': 1260},
   {'자격_대분류': 'F1', '외국인수': 1382},
   {'자격_대분류': 'F2', '외국인수': 794},
   {'자격_대분류': 'F3', '외국인수': 1014},
   {'자격_대분류': 'F4', '외국인수': 3380},
   {'자격_대분류': 'F5', '외국인수': 1633},
   {'자격_대분류': 'F6', '외국인수': 2985},
   {'자격_대분류': 'G1', '외국인수': 624},
   {'자격_대분류': 'H1', '외국인수': 19},
   {'자격_대분류': 'H2', '외국인수': 437}]},
 {'시도명': '부산광역시',
  'data': [{'자격_대분류': '0', '외국인수': 226},
   {'자격_대분류': 'A1', '외국인수': 88},
   {'자격_대분류': 'A2', '외국인수': 123},
   {'자격_대분류': 'A3', '외국인수': 335},
   {'자격_대분류': 'D1', '외국인수': 3},
   {'자격_대분류': 'D10', '외국인수': 1062},
   {'자격_대분류': 'D2', '외국인수': 13136},
   {'자격_대분류': 'D3', '외국인수': 85},
   {'자격_대분류': 'D4', '외국인수': 5726},
   {'자격_대분류': 'D5', '외국인수': 1},
   {'자격_대분류': 'D6', '외국인수': 89},
   {'자격_대분류': 'D7', '외국인수': 87},
   {'자격_대분류': 'D8', '외국인수': 270},
   {'자격_대분류': 'D9', '외국인수': 148},
   {'자격_대분류': 'E1', '외국인수': 108},
   {'자격_대분류': 'E10', '외국인수': 3296},
   {'자격_대분류': 'E2', '외국인수': 885},
   {'자격_대분류': 'E3', '외국인수': 184},
   {'자격_대분류': 'E4', '외국인수': 5},
   {'자격_대분류': 'E5', '외국인수': 1},
   {'자격_대분류': 'E6', '외국인수': 266},
   {'자격_대분류': 'E7', '외국인수': 2362},
   {'자격_대분류': 'E8', '외국인수': 28},
   {'자격_대분류': 'E9', '외국인수': 9497},
   {'자격_대분류': 'F1', '외국인수': 2720},
   {'자격_대분류': 'F2', '외국인수': 1442},
   {'자격_대분류': 'F3', '외국인수': 1737},
   {'자격_대분류': 'F4', '외국인수': 7485},
   {'자격_대분류': 'F5', '외국인수': 3843},
   {'자격_대분류': 'F6', '외국인수': 6429},
   {'자격_대분류': 'G1', '외국인수': 888},
   {'자격_대분류': 'H1', '외국인수': 145},
   {'자격_대분류': 'H2', '외국인수': 590}]},
 {'시도명': '서울특별시',
  'data': [{'자격_대분류': '0', '외국인수': 1500},
   {'자격_대분류': 'A1', '외국인수': 4299},
   {'자격_대분류': 'A2', '외국인수': 1986},
   {'자격_대분류': 'A3', '외국인수': 1717},
   {'자격_대분류': 'D1', '외국인수': 29},
   {'자격_대분류': 'D10', '외국인수': 6256},
   {'자격_대분류': 'D2', '외국인수': 63328},
   {'자격_대분류': 'D3', '외국인수': 38},
   {'자격_대분류': 'D4', '외국인수': 20345},
   {'자격_대분류': 'D5', '외국인수': 139},
   {'자격_대분류': 'D6', '외국인수': 444},
   {'자격_대분류': 'D7', '외국인수': 529},
   {'자격_대분류': 'D8', '외국인수': 3119},
   {'자격_대분류': 'D9', '외국인수': 405},
   {'자격_대분류': 'E1', '외국인수': 486},
   {'자격_대분류': 'E10', '외국인수': 2},
   {'자격_대분류': 'E2', '외국인수': 3644},
   {'자격_대분류': 'E3', '외국인수': 790},
   {'자격_대분류': 'E4', '외국인수': 40},
   {'자격_대분류': 'E5', '외국인수': 199},
   {'자격_대분류': 'E6', '외국인수': 1528},
   {'자격_대분류': 'E7', '외국인수': 8010},
   {'자격_대분류': 'E8', '외국인수': 6},
   {'자격_대분류': 'E9', '외국인수': 3130},
   {'자격_대분류': 'F1', '외국인수': 12309},
   {'자격_대분류': 'F2', '외국인수': 15193},
   {'자격_대분류': 'F3', '외국인수': 9229},
   {'자격_대분류': 'F4', '외국인수': 147773},
   {'자격_대분류': 'F5', '외국인수': 51045},
   {'자격_대분류': 'F6', '외국인수': 22367},
   {'자격_대분류': 'G1', '외국인수': 5120},
   {'자격_대분류': 'H1', '외국인수': 2745},
   {'자격_대분류': 'H2', '외국인수': 25567}]},
 {'시도명': '세종특별자치시',
  'data': [{'자격_대분류': '0', '외국인수': 41},
   {'자격_대분류': 'A1', '외국인수': 2},
   {'자격_대분류': 'A2', '외국인수': 3},
   {'자격_대분류': 'A3', '외국인수': 3},
   {'자격_대분류': 'D10', '외국인수': 50},
   {'자격_대분류': 'D2', '외국인수': 904},
   {'자격_대분류': 'D3', '외국인수': 1},
   {'자격_대분류': 'D4', '외국인수': 476},
   {'자격_대분류': 'D6', '외국인수': 1},
   {'자격_대분류': 'D7', '외국인수': 1},
   {'자격_대분류': 'D8', '외국인수': 10},
   {'자격_대분류': 'D9', '외국인수': 3},
   {'자격_대분류': 'E1', '외국인수': 12},
   {'자격_대분류': 'E2', '외국인수': 175},
   {'자격_대분류': 'E3', '외국인수': 12},
   {'자격_대분류': 'E4', '외국인수': 1},
   {'자격_대분류': 'E6', '외국인수': 1},
   {'자격_대분류': 'E7', '외국인수': 247},
   {'자격_대분류': 'E8', '외국인수': 40},
   {'자격_대분류': 'E9', '외국인수': 1739},
   {'자격_대분류': 'F1', '외국인수': 377},
   {'자격_대분류': 'F2', '외국인수': 125},
   {'자격_대분류': 'F3', '외국인수': 133},
   {'자격_대분류': 'F4', '외국인수': 1445},
   {'자격_대분류': 'F5', '외국인수': 498},
   {'자격_대분류': 'F6', '외국인수': 759},
   {'자격_대분류': 'G1', '외국인수': 304},
   {'자격_대분류': 'H1', '외국인수': 5},
   {'자격_대분류': 'H2', '외국인수': 259}]},
 {'시도명': '울산광역시',
  'data': [{'자격_대분류': '0', '외국인수': 144},
   {'자격_대분류': 'A2', '외국인수': 8},
   {'자격_대분류': 'A3', '외국인수': 3},
   {'자격_대분류': 'D10', '외국인수': 248},
   {'자격_대분류': 'D2', '외국인수': 1152},
   {'자격_대분류': 'D3', '외국인수': 213},
   {'자격_대분류': 'D4', '외국인수': 491},
   {'자격_대분류': 'D6', '외국인수': 27},
   {'자격_대분류': 'D7', '외국인수': 19},
   {'자격_대분류': 'D8', '외국인수': 65},
   {'자격_대분류': 'D9', '외국인수': 171},
   {'자격_대분류': 'E1', '외국인수': 20},
   {'자격_대분류': 'E10', '외국인수': 444},
   {'자격_대분류': 'E2', '외국인수': 228},
   {'자격_대분류': 'E3', '외국인수': 138},
   {'자격_대분류': 'E4', '외국인수': 2},
   {'자격_대분류': 'E6', '외국인수': 52},
   {'자격_대분류': 'E7', '외국인수': 4707},
   {'자격_대분류': 'E9', '외국인수': 7223},
   {'자격_대분류': 'F1', '외국인수': 1777},
   {'자격_대분류': 'F2', '외국인수': 1036},
   {'자격_대분류': 'F3', '외국인수': 976},
   {'자격_대분류': 'F4', '외국인수': 6526},
   {'자격_대분류': 'F5', '외국인수': 3254},
   {'자격_대분류': 'F6', '외국인수': 2947},
   {'자격_대분류': 'G1', '외국인수': 1175},
   {'자격_대분류': 'H1', '외국인수': 15},
   {'자격_대분류': 'H2', '외국인수': 1107}]},
 {'시도명': '인천광역시',
  'data': [{'자격_대분류': '0', '외국인수': 519},
   {'자격_대분류': 'A1', '외국인수': 108},
   {'자격_대분류': 'A2', '외국인수': 569},
   {'자격_대분류': 'A3', '외국인수': 17},
   {'자격_대분류': 'D1', '외국인수': 4},
   {'자격_대분류': 'D10', '외국인수': 652},
   {'자격_대분류': 'D2', '외국인수': 5460},
   {'자격_대분류': 'D3', '외국인수': 40},
   {'자격_대분류': 'D4', '외국인수': 2526},
   {'자격_대분류': 'D6', '외국인수': 59},
   {'자격_대분류': 'D7', '외국인수': 72},
   {'자격_대분류': 'D8', '외국인수': 1389},
   {'자격_대분류': 'D9', '외국인수': 208},
   {'자격_대분류': 'E1', '외국인수': 124},
   {'자격_대분류': 'E10', '외국인수': 309},
   {'자격_대분류': 'E2', '외국인수': 554},
   {'자격_대분류': 'E3', '외국인수': 117},
   {'자격_대분류': 'E4', '외국인수': 121},
   {'자격_대분류': 'E5', '외국인수': 11},
   {'자격_대분류': 'E6', '외국인수': 95},
   {'자격_대분류': 'E7', '외국인수': 2490},
   {'자격_대분류': 'E9', '외국인수': 14664},
   {'자격_대분류': 'F1', '외국인수': 7730},
   {'자격_대분류': 'F2', '외국인수': 5789},
   {'자격_대분류': 'F3', '외국인수': 4524},
   {'자격_대분류': 'F4', '외국인수': 43637},
   {'자격_대분류': 'F5', '외국인수': 19601},
   {'자격_대분류': 'F6', '외국인수': 10901},
   {'자격_대분류': 'G1', '외국인수': 4610},
   {'자격_대분류': 'H1', '외국인수': 89},
   {'자격_대분류': 'H2', '외국인수': 5777}]},
 {'시도명': '전라남도',
  'data': [{'자격_대분류': '0', '외국인수': 270},
   {'자격_대분류': 'A2', '외국인수': 73},
   {'자격_대분류': 'A3', '외국인수': 3},
   {'자격_대분류': 'D10', '외국인수': 410},
   {'자격_대분류': 'D2', '외국인수': 3518},
   {'자격_대분류': 'D3', '외국인수': 4},
   {'자격_대분류': 'D4', '외국인수': 2054},
   {'자격_대분류': 'D6', '외국인수': 61},
   {'자격_대분류': 'D7', '외국인수': 15},
   {'자격_대분류': 'D8', '외국인수': 284},
   {'자격_대분류': 'D9', '외국인수': 126},
   {'자격_대분류': 'E1', '외국인수': 20},
   {'자격_대분류': 'E10', '외국인수': 3907},
   {'자격_대분류': 'E2', '외국인수': 412},
   {'자격_대분류': 'E3', '외국인수': 82},
   {'자격_대분류': 'E6', '외국인수': 25},
   {'자격_대분류': 'E7', '외국인수': 2722},
   {'자격_대분류': 'E8', '외국인수': 5769},
   {'자격_대분류': 'E9', '외국인수': 22070},
   {'자격_대분류': 'F1', '외국인수': 3481},
   {'자격_대분류': 'F2', '외국인수': 694},
   {'자격_대분류': 'F3', '외국인수': 1134},
   {'자격_대분류': 'F4', '외국인수': 4049},
   {'자격_대분류': 'F5', '외국인수': 2058},
   {'자격_대분류': 'F6', '외국인수': 5752},
   {'자격_대분류': 'G1', '외국인수': 1701},
   {'자격_대분류': 'H1', '외국인수': 6},
   {'자격_대분류': 'H2', '외국인수': 538}]},
 {'시도명': '전라북도',
  'data': [{'자격_대분류': 'A3', '외국인수': 75}, {'자격_대분류': 'D4', '외국인수': 1}]},
 {'시도명': '전북특별자치도',
  'data': [{'자격_대분류': '0', '외국인수': 299},
   {'자격_대분류': 'A3', '외국인수': 174},
   {'자격_대분류': 'D10', '외국인수': 842},
   {'자격_대분류': 'D2', '외국인수': 6785},
   {'자격_대분류': 'D3', '외국인수': 48},
   {'자격_대분류': 'D4', '외국인수': 3887},
   {'자격_대분류': 'D6', '외국인수': 43},
   {'자격_대분류': 'D7', '외국인수': 2},
   {'자격_대분류': 'D8', '외국인수': 121},
   {'자격_대분류': 'D9', '외국인수': 56},
   {'자격_대분류': 'E1', '외국인수': 27},
   {'자격_대분류': 'E10', '외국인수': 409},
   {'자격_대분류': 'E2', '외국인수': 380},
   {'자격_대분류': 'E3', '외국인수': 158},
   {'자격_대분류': 'E6', '외국인수': 24},
   {'자격_대분류': 'E7', '외국인수': 1444},
   {'자격_대분류': 'E8', '외국인수': 1626},
   {'자격_대분류': 'E9', '외국인수': 12355},
   {'자격_대분류': 'F1', '외국인수': 2989},
   {'자격_대분류': 'F2', '외국인수': 1238},
   {'자격_대분류': 'F3', '외국인수': 1502},
   {'자격_대분류': 'F4', '외국인수': 4295},
   {'자격_대분류': 'F5', '외국인수': 2234},
   {'자격_대분류': 'F6', '외국인수': 5065},
   {'자격_대분류': 'G1', '외국인수': 1411},
   {'자격_대분류': 'H1', '외국인수': 16},
   {'자격_대분류': 'H2', '외국인수': 584}]},
 {'시도명': '제주특별자치도',
  'data': [{'자격_대분류': '0', '외국인수': 100},
   {'자격_대분류': 'A1', '외국인수': 36},
   {'자격_대분류': 'A2', '외국인수': 9},
   {'자격_대분류': 'A3', '외국인수': 21},
   {'자격_대분류': 'D1', '외국인수': 3},
   {'자격_대분류': 'D10', '외국인수': 246},
   {'자격_대분류': 'D2', '외국인수': 1048},
   {'자격_대분류': 'D4', '외국인수': 566},
   {'자격_대분류': 'D6', '외국인수': 35},
   {'자격_대분류': 'D7', '외국인수': 10},
   {'자격_대분류': 'D8', '외국인수': 103},
   {'자격_대분류': 'D9', '외국인수': 6},
   {'자격_대분류': 'E1', '외국인수': 9},
   {'자격_대분류': 'E10', '외국인수': 3245},
   {'자격_대분류': 'E2', '외국인수': 252},
   {'자격_대분류': 'E3', '외국인수': 34},
   {'자격_대분류': 'E6', '외국인수': 175},
   {'자격_대분류': 'E7', '외국인수': 4119},
   {'자격_대분류': 'E8', '외국인수': 793},
   {'자격_대분류': 'E9', '외국인수': 4766},
   {'자격_대분류': 'F1', '외국인수': 1340},
   {'자격_대분류': 'F2', '외국인수': 2519},
   {'자격_대분류': 'F3', '외국인수': 701},
   {'자격_대분류': 'F4', '외국인수': 3511},
   {'자격_대분류': 'F5', '외국인수': 3639},
   {'자격_대분류': 'F6', '외국인수': 2641},
   {'자격_대분류': 'G1', '외국인수': 1158},
   {'자격_대분류': 'H1', '외국인수': 17},
   {'자격_대분류': 'H2', '외국인수': 399}]},
 {'시도명': '충청남도',
  'data': [{'자격_대분류': '0', '외국인수': 629},
   {'자격_대분류': 'A2', '외국인수': 4},
   {'자격_대분류': 'A3', '외국인수': 1237},
   {'자격_대분류': 'D10', '외국인수': 801},
   {'자격_대분류': 'D2', '외국인수': 8574},
   {'자격_대분류': 'D3', '외국인수': 76},
   {'자격_대분류': 'D4', '외국인수': 4770},
   {'자격_대분류': 'D6', '외국인수': 126},
   {'자격_대분류': 'D7', '외국인수': 13},
   {'자격_대분류': 'D8', '외국인수': 199},
   {'자격_대분류': 'D9', '외국인수': 61},
   {'자격_대분류': 'E1', '외국인수': 58},
   {'자격_대분류': 'E10', '외국인수': 2113},
   {'자격_대분류': 'E2', '외국인수': 547},
   {'자격_대분류': 'E3', '외국인수': 84},
   {'자격_대분류': 'E4', '외국인수': 2},
   {'자격_대분류': 'E5', '외국인수': 1},
   {'자격_대분류': 'E6', '외국인수': 34},
   {'자격_대분류': 'E7', '외국인수': 3272},
   {'자격_대분류': 'E8', '외국인수': 3094},
   {'자격_대분류': 'E9', '외국인수': 30040},
   {'자격_대분류': 'F1', '외국인수': 7857},
   {'자격_대분류': 'F2', '외국인수': 3003},
   {'자격_대분류': 'F3', '외국인수': 2951},
   {'자격_대분류': 'F4', '외국인수': 34193},
   {'자격_대분류': 'F5', '외국인수': 9239},
   {'자격_대분류': 'F6', '외국인수': 8121},
   {'자격_대분류': 'G1', '외국인수': 4352},
   {'자격_대분류': 'H1', '외국인수': 36},
   {'자격_대분류': 'H2', '외국인수': 5393}]},
 {'시도명': '충청북도',
  'data': [{'자격_대분류': '0', '외국인수': 403},
   {'자격_대분류': 'A2', '외국인수': 7},
   {'자격_대분류': 'A3', '외국인수': 4},
   {'자격_대분류': 'D1', '외국인수': 1},
   {'자격_대분류': 'D10', '외국인수': 351},
   {'자격_대분류': 'D2', '외국인수': 6135},
   {'자격_대분류': 'D3', '외국인수': 63},
   {'자격_대분류': 'D4', '외국인수': 2431},
   {'자격_대분류': 'D6', '외국인수': 39},
   {'자격_대분류': 'D7', '외국인수': 28},
   {'자격_대분류': 'D8', '외국인수': 274},
   {'자격_대분류': 'D9', '외국인수': 57},
   {'자격_대분류': 'E1', '외국인수': 24},
   {'자격_대분류': 'E10', '외국인수': 1},
   {'자격_대분류': 'E2', '외국인수': 302},
   {'자격_대분류': 'E3', '외국인수': 67},
   {'자격_대분류': 'E6', '외국인수': 21},
   {'자격_대분류': 'E7', '외국인수': 2463},
   {'자격_대분류': 'E8', '외국인수': 403},
   {'자격_대분류': 'E9', '외국인수': 20089},
   {'자격_대분류': 'F1', '외국인수': 4317},
   {'자격_대분류': 'F2', '외국인수': 1693},
   {'자격_대분류': 'F3', '외국인수': 1944},
   {'자격_대분류': 'F4', '외국인수': 16418},
   {'자격_대분류': 'F5', '외국인수': 4419},
   {'자격_대분류': 'F6', '외국인수': 5056},
   {'자격_대분류': 'G1', '외국인수': 3171},
   {'자격_대분류': 'H1', '외국인수': 14},
   {'자격_대분류': 'H2', '외국인수': 2524}]}]

In [ ]:
with open("C:/HANSSAK/SecureGate/download/분석본_250528_장기체류(등록거소)_전처리.json", "w", encoding='utf-8') as f:
    json.dump(result, f, ensure_ascii=False, indent=2)

### excel에 자격_코드명 특성 추가

In [12]:
kor_title = pd.read_excel("C:/HANSSAK/SecureGate/download/250529_대분류자격코드명_메타.xlsx")
kor_title

   자격_대분류    LW_NM
0       0     자격없음
1      A1       외교
2      A2       공무
3      A3       협정
4      B1     사증면제
5      B2     관광통과
6      C1     일시취재
7      C2     단기상용
8      C3     단기방문
9      C4     단기취업
10     D1     문화예술
11    D10       구직
12     D2       유학
13     D3     기술연수
14     D4     일반연수
15     D5       취재
16     D6       종교
17     D7       주재
18     D8     기업투자
19     D9     무역경영
20     E1       교수
21    E10     선원취업
22     E2       회화
23     E3       연구
24     E4     기술지도
25     E5     전문직업
26     E6     예술흥행
27     E7     특정활동
28     E8     계절근로
29     E8     연수취업
30     E9    비전문취업
31     F1     방문동거
32     F2       거주
33     F3       동반
34     F4     재외동포
35     F5       영주
36     F6     결혼이민
37     G1       기타
38     H1     관광취업
39     H2     방문취업
40     T1     관광상륙
41     T2  조건부입국허가

In [13]:
kor_dict = dict(zip(kor_title['자격_대분류'], kor_title['LW_NM']))
kor_dict

{0: '자격없음',
 'A1': '외교',
 'A2': '공무',
 'A3': '협정',
 'B1': '사증면제',
 'B2': '관광통과',
 'C1': '일시취재',
 'C2': '단기상용',
 'C3': '단기방문',
 'C4': '단기취업',
 'D1': '문화예술',
 'D10': '구직',
 'D2': '유학',
 'D3': '기술연수',
 'D4': '일반연수',
 'D5': '취재',
 'D6': '종교',
 'D7': '주재',
 'D8': '기업투자',
 'D9': '무역경영',
 'E1': '교수',
 'E10': '선원취업',
 'E2': '회화',
 'E3': '연구',
 'E4': '기술지도',
 'E5': '전문직업',
 'E6': '예술흥행',
 'E7': '특정활동',
 'E8': '연수취업',
 'E9': '비전문취업',
 'F1': '방문동거',
 'F2': '거주',
 'F3': '동반',
 'F4': '재외동포',
 'F5': '영주',
 'F6': '결혼이민',
 'G1': '기타',
 'H1': '관광취업',
 'H2': '방문취업',
 'T1': '관광상륙',
 'T2': '조건부입국허가'}

In [14]:
# 기존 df에 자격_코드명 특성 추가 후 map으로 연결
df['자격_코드명'] = df['자격_대분류'].map(kor_dict)
df

         시도명 자격_대분류  외국인수 자격_코드명
0    강원특별자치도      0   112    NaN
1    강원특별자치도     A3    12     협정
2    강원특별자치도     D1     1   문화예술
3    강원특별자치도    D10   332     구직
4    강원특별자치도     D2  5178     유학
..       ...    ...   ...    ...
501     충청북도     F5  4419     영주
502     충청북도     F6  5056   결혼이민
503     충청북도     G1  3171     기타
504     충청북도     H1    14   관광취업
505     충청북도     H2  2524   방문취업

[506 rows x 4 columns]

In [17]:
df.loc[df['자격_대분류'] == '0', '자격_코드명'] = '자격없음'
df

         시도명 자격_대분류  외국인수 자격_코드명
0    강원특별자치도      0   112   자격없음
1    강원특별자치도     A3    12     협정
2    강원특별자치도     D1     1   문화예술
3    강원특별자치도    D10   332     구직
4    강원특별자치도     D2  5178     유학
..       ...    ...   ...    ...
501     충청북도     F5  4419     영주
502     충청북도     F6  5056   결혼이민
503     충청북도     G1  3171     기타
504     충청북도     H1    14   관광취업
505     충청북도     H2  2524   방문취업

[506 rows x 4 columns]

In [19]:
df.to_csv("C:/HANSSAK/SecureGate/download/코드명추가_202412_장기체류(등록거소)_전처리.csv", index=False, encoding='cp949')
df

         시도명 자격_대분류  외국인수 자격_코드명
0    강원특별자치도      0   112   자격없음
1    강원특별자치도     A3    12     협정
2    강원특별자치도     D1     1   문화예술
3    강원특별자치도    D10   332     구직
4    강원특별자치도     D2  5178     유학
..       ...    ...   ...    ...
501     충청북도     F5  4419     영주
502     충청북도     F6  5056   결혼이민
503     충청북도     G1  3171     기타
504     충청북도     H1    14   관광취업
505     충청북도     H2  2524   방문취업

[506 rows x 4 columns]