### 경기도, E8 시군으로 나누기

In [1]:
import pandas as pd
import numpy as np

In [ ]:
df_gg = pd.read_csv("C:/HANSSAK/SecureGate/Download/Treemap_2504_2505_경기도.csv", encoding='cp949')

### gg

In [3]:
df_gg

     시군구명  시군명 자격_대분류 자격_코드명  202504_외국인수  202505_외국인수  2504to2505
0     가평군  가평군      0   자격없음            6            6        0.00
1     가평군  가평군    D10     구직           17           16       -5.88
2     가평군  가평군     D2     유학           39           42        7.69
3     가평군  가평군     D4   일반연수           38           35       -7.89
4     가평군  가평군     D6     종교           11           11        0.00
...   ...  ...    ...    ...          ...          ...         ...
1069  화성시  화성시     F5     영주         5414         5481        1.24
1070  화성시  화성시     F6   결혼이민         3790         3796        0.16
1071  화성시  화성시     G1     기타         2063         2092        1.41
1072  화성시  화성시     H1   관광취업           17           15      -11.76
1073  화성시  화성시     H2   방문취업         2440         2407       -1.35

[1074 rows x 7 columns]

In [21]:
# 예시: df에 '시군명', '시군구명' 컬럼이 있다고 가정
multi_sgg = df_gg.groupby('시군명')['시군구명'].nunique().reset_index()

# 시군구명이 2개 이상 있는 시군명만 필터링
multi_sgg = multi_sgg[multi_sgg['시군구명'] > 1]

In [22]:
multi_sgg

    시군명  시군구명
1   고양시     3
10  부천시     3
11  성남시     3
12  수원시     4
14  안산시     2
16  안양시     2
22  용인시     3

In [28]:
df_gg[df_gg['시군명']=="부천시"]

        시군구명  시군명 자격_대분류 자격_코드명  202504_외국인수  202505_외국인수  2504to2505
293  부천시 소사구  부천시      0   자격없음           15           14       -6.67
294  부천시 소사구  부천시     A2     공무            1            1        0.00
295  부천시 소사구  부천시    D10     구직           22           20       -9.09
296  부천시 소사구  부천시     D2     유학          264          268        1.52
297  부천시 소사구  부천시     D4   일반연수          279          276       -1.08
..       ...  ...    ...    ...          ...          ...         ...
358  부천시 원미구  부천시     F5     영주         5511         5570        1.07
359  부천시 원미구  부천시     F6   결혼이민         1483         1490        0.47
360  부천시 원미구  부천시     G1     기타          267          260       -2.62
361  부천시 원미구  부천시     H1   관광취업           15           17       13.33
362  부천시 원미구  부천시     H2   방문취업         1344         1362        1.34

[70 rows x 7 columns]

In [29]:
df_gg_grouped = df_gg.groupby(['시군명', '자격_대분류', '자격_코드명'])[
    ['202504_외국인수', '202505_외국인수']
].sum().reset_index()

df_gg_grouped

     시군명 자격_대분류 자격_코드명  202504_외국인수  202505_외국인수
0    가평군      0   자격없음            6            6
1    가평군    D10     구직           17           16
2    가평군     D2     유학           39           42
3    가평군     D4   일반연수           38           35
4    가평군     D6     종교           11           11
..   ...    ...    ...          ...          ...
761  화성시     F5     영주         5414         5481
762  화성시     F6   결혼이민         3790         3796
763  화성시     G1     기타         2063         2092
764  화성시     H1   관광취업           17           15
765  화성시     H2   방문취업         2440         2407

[766 rows x 5 columns]

#### 2504to2505 추가

In [32]:
# 안전한 계산을 위해 0으로 나누는 경우 대비
def calc_rate_change(new, old):
    return (new - old) / old if old != 0 else None

# 증감률 계산
df_gg_grouped["2504to2505"] = (((df_gg_grouped["202505_외국인수"] - df_gg_grouped["202504_외국인수"]) / df_gg_grouped["202504_외국인수"]) * 100).round(2)

df_gg_grouped

     시군명 자격_대분류 자격_코드명  202504_외국인수  202505_외국인수  2504to2505
0    가평군      0   자격없음            6            6        0.00
1    가평군    D10     구직           17           16       -5.88
2    가평군     D2     유학           39           42        7.69
3    가평군     D4   일반연수           38           35       -7.89
4    가평군     D6     종교           11           11        0.00
..   ...    ...    ...          ...          ...         ...
761  화성시     F5     영주         5414         5481        1.24
762  화성시     F6   결혼이민         3790         3796        0.16
763  화성시     G1     기타         2063         2092        1.41
764  화성시     H1   관광취업           17           15      -11.76
765  화성시     H2   방문취업         2440         2407       -1.35

[766 rows x 6 columns]

#### 경기도 완료

In [33]:
df_gg_grouped.to_csv("C:/HANSSAK/SecureGate/Download/Treemap_2504_2505_경기도_전처리.csv", encoding='cp949', index=False)

### E8 비자

In [61]:
df_E8 = pd.read_csv("C:/HANSSAK/SecureGate/Download/250609_장기체류(등록+거소)외국인_데이터셋(202504_05)_세종시....csv", encoding='cp949')
df_E8

          기준년월      시도명 시군구명 대분류자격 소분류자격       국적  외국인수
0       202504  강원특별자치도  강릉시    00    00  러시아(연방)    14
1       202504  강원특별자치도  강릉시    00    00      모로코     1
2       202504  강원특별자치도  강릉시    00    00    방글라데시     1
3       202504  강원특별자치도  강릉시    00    00     스리랑카     1
4       202504  강원특별자치도  강릉시    00    00   우즈베키스탄     4
...        ...      ...  ...   ...   ...      ...   ...
233781  202505     충청북도  충주시    H2    71    우크라이나     1
233782  202505     충청북도  충주시    H2    71   한국계중국인     7
233783  202505     충청북도  충주시    H2    72   한국계중국인    13
233784  202505     충청북도  충주시    H2    91   한국계중국인     4
233785  202505     충청북도  충주시    H2    99   한국계중국인     6

[233786 rows x 7 columns]

In [62]:
df_E8 = df_E8[df_E8['대분류자격']=="E8"]
df_E8['자격_코드명'] = "계절근로"
df_E8

C:\Users\admin\AppData\Local\Temp\ipykernel_9256\3209134841.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_E8['자격_코드명'] = "계절근로"

          기준년월      시도명     시군구명 대분류자격 소분류자격    국적  외국인수 자격_코드명
130     202504  강원특별자치도      강릉시    E8    01   라오스    63   계절근로
131     202504  강원특별자치도      강릉시    E8    02   베트남    44   계절근로
132     202504  강원특별자치도      강릉시    E8    02  캄보디아     3   계절근로
512     202504  강원특별자치도      고성군    E8    02   베트남    13   계절근로
845     202504  강원특별자치도      삼척시    E8    01   필리핀    27   계절근로
...        ...      ...      ...   ...   ...   ...   ...    ...
232793  202505     충청북도  청주시 흥덕구    E8    03   라오스     1   계절근로
233422  202505     충청북도      충주시    E8    01   라오스    60   계절근로
233423  202505     충청북도      충주시    E8    01  캄보디아   163   계절근로
233424  202505     충청북도      충주시    E8    02   베트남    86   계절근로
233425  202505     충청북도      충주시    E8    02    중국     1   계절근로

[1413 rows x 8 columns]

In [63]:
df_E8_202504 = df_E8.loc[df_E8['기준년월'] == 202504, ['시도명','시군구명','대분류자격','외국인수','자격_코드명']]
df_E8_202504

            시도명     시군구명 대분류자격  외국인수 자격_코드명
130     강원특별자치도      강릉시    E8    63   계절근로
131     강원특별자치도      강릉시    E8    44   계절근로
132     강원특별자치도      강릉시    E8     3   계절근로
512     강원특별자치도      고성군    E8    13   계절근로
845     강원특별자치도      삼척시    E8    27   계절근로
...         ...      ...   ...   ...    ...
115638     충청북도  청주시 흥덕구    E8     1   계절근로
115639     충청북도  청주시 흥덕구    E8     2   계절근로
116265     충청북도      충주시    E8    13   계절근로
116266     충청북도      충주시    E8    70   계절근로
116267     충청북도      충주시    E8    70   계절근로

[669 rows x 5 columns]

In [64]:
df_E8_202504['시군구명'] = df_E8_202504['시군구명'].str.split(" ").str[0]
df_E8_202504

            시도명 시군구명 대분류자격  외국인수 자격_코드명
130     강원특별자치도  강릉시    E8    63   계절근로
131     강원특별자치도  강릉시    E8    44   계절근로
132     강원특별자치도  강릉시    E8     3   계절근로
512     강원특별자치도  고성군    E8    13   계절근로
845     강원특별자치도  삼척시    E8    27   계절근로
...         ...  ...   ...   ...    ...
115638     충청북도  청주시    E8     1   계절근로
115639     충청북도  청주시    E8     2   계절근로
116265     충청북도  충주시    E8    13   계절근로
116266     충청북도  충주시    E8    70   계절근로
116267     충청북도  충주시    E8    70   계절근로

[669 rows x 5 columns]

In [41]:
df_E8_202505 = df_E8.loc[df_E8['기준년월'] == 202505, ['시도명','시군구명','대분류자격','외국인수','자격_코드명']]
df_E8_202505

            시도명     시군구명 대분류자격  외국인수 자격_코드명
116753  강원특별자치도      강릉시    E8    66   계절근로
116754  강원특별자치도      강릉시    E8    48   계절근로
116755  강원특별자치도      강릉시    E8     3   계절근로
117137  강원특별자치도      고성군    E8    16   계절근로
117279  강원특별자치도      동해시    E8     3   계절근로
...         ...      ...   ...   ...    ...
232793     충청북도  청주시 흥덕구    E8     1   계절근로
233422     충청북도      충주시    E8    60   계절근로
233423     충청북도      충주시    E8   163   계절근로
233424     충청북도      충주시    E8    86   계절근로
233425     충청북도      충주시    E8     1   계절근로

[744 rows x 5 columns]

In [65]:
df_E8_202505['시군구명'] = df_E8_202505['시군구명'].str.split(" ").str[0]
df_E8_202505

            시도명 시군구명 대분류자격  외국인수 자격_코드명
116753  강원특별자치도  강릉시    E8    66   계절근로
116754  강원특별자치도  강릉시    E8    48   계절근로
116755  강원특별자치도  강릉시    E8     3   계절근로
117137  강원특별자치도  고성군    E8    16   계절근로
117279  강원특별자치도  동해시    E8     3   계절근로
...         ...  ...   ...   ...    ...
232793     충청북도  청주시    E8     1   계절근로
233422     충청북도  충주시    E8    60   계절근로
233423     충청북도  충주시    E8   163   계절근로
233424     충청북도  충주시    E8    86   계절근로
233425     충청북도  충주시    E8     1   계절근로

[744 rows x 5 columns]

In [67]:
# 예시: df에 '시군명', '시군구명' 컬럼이 있다고 가정
multi_sgg = df_E8_202505.groupby('시군구명')['시도명'].nunique().reset_index()

# 시군구명이 2개 이상 있는 시군명만 필터링
multi_sgg = multi_sgg[multi_sgg['시도명'] > 1]

In [68]:
multi_sgg

   시군구명  시도명
9   고성군    2
40   동구    2
55   북구    2

In [74]:
df_E8_202504[df_E8_202504['시군구명'] == "고성군"]

       시도명 시군구명 자격_대분류 자격_코드명  외국인수
0  강원특별자치도  고성군     E8   계절근로    13
1     경상남도  고성군     E8   계절근로   152

In [ ]:
df_E8_202504.rename(columns={'대분류자격': '자격_대분류'}, inplace=True)
df_E8_202505.rename(columns={'대분류자격': '자격_대분류'}, inplace=True)

In [ ]:
df_E8_202504.loc[df_E8_202504['시도명', '시군구명'] == ["강원특별자치도도", "고성군"], '시군구명'] = "고성_강원"
df_E8_202504.loc[df_E8_202504['시군구명'] == "고성군", '시군구명'] = "고성_강원"